### ISSUE TITLE
[Question]: Database implementation

### ISSUE THREAD

**Issue by thomas-mauran** [dev-sys-do/orka#15]
### Question from controller team to @sameo : 
Regarding the database implementation, we figured out we need a key-value database to store the workload's states. We thought about using `etcd` like Kubernetes  but it doesn't seem to handle streams. So we were wondering if it would be better to use Redis instead or even both. 

For example, use Redis to handle streams and store the data in `etcd`

**Comment by sameo** [comment]
> ### Question from controller team to @sameo :
> 
> Regarding the database implementation, we figured out we need a key-value database to store the workload's states. We thought about using `etcd` like Kubernetes but it doesn't seem to handle streams. So we were wondering if it would be better to use Redis instead or even both.
> 
> For example, use Redis to handle streams and store the data in `etcd`

You can keep your streamed updates in memory (a hashmap for example) and do batch updates to your KV store. It may sound racy but it can be made safe if the scheduler syncs with the controller when the controller recovers.
For now, I suggest that you keep your stream updates in memory (as I said, a hashmap) and then use something simple like [kv](https://docs.rs/kv/latest/kv/) to store your data in a file based DB. Does that make sense?

**Comment by thomas-mauran** [comment]
> > ### Question from controller team to @sameo :
> > Regarding the database implementation, we figured out we need a key-value database to store the workload's states. We thought about using `etcd` like Kubernetes but it doesn't seem to handle streams. So we were wondering if it would be better to use Redis instead or even both.
> > For example, use Redis to handle streams and store the data in `etcd`
> 
> You can keep your streamed updates in memory (a hashmap for example) and do batch updates to your KV store. It may sound racy but it can be made safe if the scheduler syncs with the controller when the controller recovers. For now, I suggest that you keep your stream updates in memory (as I said, a hashmap) and then use something simple like [kv](https://docs.rs/kv/latest/kv/) to store your data in a file based DB. Does that make sense?

Thanks for your answer, kv looks like a great and easy alternative, I'm letting @sea-gull-diana and @charley04310 give their opinion on that

**Comment by sea-gull-diana** [comment]
> > ### Question from controller team to @sameo :
> > Regarding the database implementation, we figured out we need a key-value database to store the workload's states. We thought about using `etcd` like Kubernetes but it doesn't seem to handle streams. So we were wondering if it would be better to use Redis instead or even both.
> > For example, use Redis to handle streams and store the data in `etcd`
> 
> You can keep your streamed updates in memory (a hashmap for example) and do batch updates to your KV store. It may sound racy but it can be made safe if the scheduler syncs with the controller when the controller recovers. For now, I suggest that you keep your stream updates in memory (as I said, a hashmap) and then use something simple like [kv](https://docs.rs/kv/latest/kv/) to store your data in a file based DB. Does that make sense?

Thank you for the reply. So the idea is to send data to the db at some regular intervals and in between keep the new updates in memory ? I'm not sure that I understood the part about safety though. When the controller recovers, wouldn't the in-memory data be lost anyway, or is the scheduler supposed to save it somehow and resend it later?

**Comment by sameo** [comment]
> > > ### Question from controller team to @sameo :
> > > Regarding the database implementation, we figured out we need a key-value database to store the workload's states. We thought about using `etcd` like Kubernetes but it doesn't seem to handle streams. So we were wondering if it would be better to use Redis instead or even both.
> > > For example, use Redis to handle streams and store the data in `etcd`
> > 
> > 
> > You can keep your streamed updates in memory (a hashmap for example) and do batch updates to your KV store. It may sound racy but it can be made safe if the scheduler syncs with the controller when the controller recovers. For now, I suggest that you keep your stream updates in memory (as I said, a hashmap) and then use something simple like [kv](https://docs.rs/kv/latest/kv/) to store your data in a file based DB. Does that make sense?
> 
> Thank you for the reply. So the idea is to send data to the db at some regular intervals and in between keep the new updates in memory ? I'm not sure that I understood the part about safety though. When the controller recovers, wouldn't the in-memory data be lost anyway, or is the scheduler supposed to save it somehow and resend it later?

This is aiming at being a stateless architecture. When one component crashes, the ones it was connected to detect it and they also detect when it reconnects. The first thing a scheduler would do when controller rejoins after crashing would be to send its latest status. Same for the scheduler with its nodes.
Please note that I'm not asking for this architecture to be implemented for now, but it should be a longer term goal. For now, keeping things in memory and syncing in batch mode is sufficient.
